name: Python tests with Allure report in GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest allure-pytest
    
    - name: Install Allure commandline
      run: |
        curl -o allure-2.22.1.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.tgz
        sudo tar -zxvf allure-2.22.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.22.1/bin/allure /usr/bin/allure
        
    - name: Run tests and generate Allure results
      run: pytest --alluredir=allure-results
    
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report
    
    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
    
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
        force_orphan: true
