name: Python tests with Allure report in GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest allure-pytest
    
    - name: Install Allure commandline
      run: |
        curl -o allure-2.13.8.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        sudo tar -zxvf allure-2.13.8.tgz -C /opt/
        sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure
        
    - name: Run tests and generate Allure results
      run: pytest --alluredir=allure-results
    
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report
    
    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
